
#WildNature configuration file
[general]

	[general.system]
		#Max *nearest* biome search radius. After exceeding this number, WildNature will search for biome ignoring radius.
		#Default: 15000
		#Range: 10 ~ 100000000
		max_search_radius = 15000
		#Should change main menu panorama?
		#Default:true
		panorama = true
		#Always use WN World Generator on server?
		#Default:true
		wn_server_gen = true
		#Special effects on join?
		#Default:true
		effect_on_join = false
		#Use new world loading screen?
		#Default:true
		worldLoadScreen = true
		#Installed mod version. Please do not change this.
		version = "2.1.6.5"
		#Send messages to users on join?
		#Default:true
		message_on_join = false
		#Should render capes?
		#Default:true
		render_capes = true

[generator]
	#River Size
	#Default: 4
	#Range: 1 ~ 20
	riverSize = 4
	#Biome Size
	#Default: 5
	#Range: 1 ~ 20
	biomeSize = 4
	#Generator version. 
	#Accepted Values: wildnature | wildnature-simplex
	generatorType = "wildnature"

	[generator.rocks]
		#Generate Rocks?
		#Default: true
		all = true
		#Rock formation chance
		#Smaller = more common
		#Default: 7
		#Range: 0 ~ 10000
		formation_chance = 7
		#Chance of rock generation
		#Default: 33
		#Range: 0 ~ 100
		chance = 33
		#Rock deposit size
		#Default: 10
		#Range: 0 ~ 100
		size = 10

		[generator.rocks.define]
			#Generate Marble?
			#If you set generator.rocks.all to FALSE, changing this has no sense
			#Default: true
			marble = true
			#Generate Basalt?
			#If you set generator.rocks.all to FALSE, changing this has no sense
			#Default: true
			basalt = true
			#Generate Limestone?
			#If you set generator.rocks.all to FALSE, changing this has no sense
			#Default: true
			limestone = true
			#Generate Pegmatite?
			#If you set generator.rocks.all to FALSE, changing this has no sense
			#Default: true
			pegmatite = true
			#Generate Conglomerate?
			#If you set generator.rocks.all to FALSE, changing this has no sense
			#Default: true
			conglomerate = true
			#Generate Gneiss?
			#If you set generator.rocks.all to FALSE, changing this has no sense
			#Default: true
			gneiss = true
			#Generate Slate?
			#If you set generator.rocks.all to FALSE, changing this has no sense
			#Default: true
			slate = true

	[generator.ores]
		#Generate Ores?
		#Default: true
		all = true
		#Amber ore rarity. Ambers generates on beaches only!!!
		#Smaller = more rare
		#Default: 3
		#Range: 0 ~ 500
		amber_rarity = 3
		#Amethyst ore rarity
		#Smaller = more rare
		#Default: 4
		#Range: 0 ~ 500
		amethyst_rarity = 4
		#Stone salt ore rarity
		#Smaller = more rare
		#Default: 7
		#Range: 0 ~ 500
		salt_stone_rarity = 7
		#Malachite ore rarity
		#Smaller = more rare
		#Default: 2
		#Range: 0 ~ 500
		malachite_rarity = 2
		#Silver ore rarity
		#Smaller = more rare
		#Default: 1
		#Range: 0 ~ 500
		silver_rarity = 1
		#Sandy salt ore rarity
		#Smaller = more rare
		#Default: 6
		#Range: 0 ~ 500
		salt_sand_rarity = 6
		#Sapphire ore rarity
		#Smaller = more rare
		#Default: 3
		#Range: 0 ~ 500
		sapphire_rarity = 3
		#Copper ore rarity
		#Smaller = more rare
		#Default: 8
		#Range: 0 ~ 500
		copper_rarity = 8
		#Ruby ore rarity
		#Warning - rubies are rare because they're generated only under oceans.
		#Smaller = more rare
		#Default: 3
		#Range: 0 ~ 500
		ruby_rarity = 3
		#Tin ore rarity
		#Smaller = more rare
		#Default: 8
		#Range: 0 ~ 500
		tin_rarity = 8

	[generator.biome]
		#Generate only WildNature biomes?
		#Default: false
		generate_only_wildnature = false
		#Insert biome ids that shouldn't generate naturally. Example - wildnature:grasslands,wildnature:bog
		blacklist = ""
		#Generate Biomes?
		#Default: true
		generate = true

		[generator.biome.feature]
			#Posion ivy & spidergrass rarity
			#Smaller = more rare
			#Default: 2
			#Range: 0 ~ 500
			ivy_rarity = 2
			#Vegetable crops spawn rarity
			#Smaller = more rare
			#Default: 2
			#Range: 0 ~ 500
			vege_crops_rarity = 2
			#Pathway noise frequency
			#Default: 0.005
			#Range: 1.0E-5 ~ 100.0
			pathway_frequency = 0.005
			#Shell generation rarity
			#Smaller = more rare
			#Default: 6
			#Range: 0 ~ 500
			shell_rarity = 6
			#River cane density
			#Smaller = less
			#Default: 50
			#Range: 0 ~ 500
			river_cane_density = 64
			#Should generate water lakes?
			#Default: true
			waterLakeGeneration = true
			#River cane rarity
			#Smaller = more rare
			#Default: 50
			#Range: 0 ~ 500
			river_cane_rarity = 50
			#Should generate cave plants like glowing mushrooms
			#Default: true
			cavePlants = true
			#Should generate lava lakes?
			#Default: true
			lavaLakeGeneration = true
			#Should generate small cacti?
			#Default: true
			small_cacti = true
			#Small cacti rarity
			#Smaller = more rare
			#Default: 5
			#Range: 0 ~ 500
			small_cacti_rarity = 5
			#Should generate poison ives & spidergrass?
			#Default: true
			special_plants = true
			#Should generate lava springs?
			#Default: true
			lavaSpringGeneration = false
			#Should generate crystals?
			#Default: true
			crystals = true
			#Should generate pebbles?
			#Default: true
			pebbles = true
			#Should generate cobweb?
			#Default: true
			cobweb = true
			#Should generate shells?
			#Default: true
			shells = true
			#Replace vanilla trees with WildNature ones?
			#Default: true
			replaceDefaultTrees = true
			#Fruit bushes spawn rarity
			#Smaller = more rare
			#Default: 3
			#Range: 0 ~ 500
			fruit_bushes_rarity = 3
			#Moss spawn rarity in forests
			#Smaller = more rare
			#Default: 4
			#Range: 0 ~ 500
			moss_rarity = 4
			#Should generate pathways?
			#Default: true
			pathways = true
			#Should generate fences near wild farms?
			#Default: true
			vege_farm_fence = true
			#Should generate moss?
			#Default: true
			moss = true
			#Vege Crop spawn chance. Spawns if random from 0 and <number> equals 0
			#Smaller = more common
			#Default: 1
			#Range: 0 ~ 500
			fruit_bushes_chance = 1
			#Should generate stalagmites?
			#Default: true
			stalagmites = true
			#Should generate vines?
			#Default: true
			vines = true
			#Should generate fruit bushes?
			#Default: true
			fruit_bushes = true
			#Should generate rock formations?
			#Default: true
			rock_formations = true
			#Should generate vege crops?
			#Default: true
			vege_crops = true
			#Moss spawn rarity in dense forests
			#Smaller = more rare
			#Default: 8
			#Range: 0 ~ 500
			moss_rarity_dense = 8
			#Should generate water springs?
			#Default: true
			waterSpringGeneration = true
			#Should generate river cane?
			#Default: true
			river_cane = true

		[generator.biome.river]
			#Depth of all of rivers
			#Default: -1.0
			#Range: -10.0 ~ 10.0
			depth = -1.0

		[generator.biome.group]
			#Chance of sub-biome spawn
			#Default: 5
			#Range: 0 ~ 10
			chance = 5
			#Size of sub-biomes
			#bigger sub-biomes = lower number
			#Default: 3
			#Range: 1 ~ 100
			size = 3

[sound]
	#[W.I.P] Ambient sounds volume
	#Range: 0.1 ~ 1.0
	volume_ambient = 1.0
	#[W.I.P] Play ambient sounds on biomes?
	play_ambient = true

[block]
	#Poison ivy poisons on walk?
	#Default: true
	poisonIvyPoison = true
	#Steam Particle max age multiplier - how long does steam live
	#Default: 10.0
	#Range: 1.0 ~ 100.0
	steam_max_age = 10.0
	#Flower disappears on walk?
	#Default: true
	flowerDisappears = true
	#Leaf fruit chance
	#Default: 10
	#Range: 0 ~ 1000
	leafFruitChance = 10
	#Flower bloom chance (Bone meal)
	#Default: 10
	#Range: 0 ~ 1000
	flowerBloomChance = 10
	#Can all veggies normally spawn on normal grass?
	#Default: false
	vegeGrassSpawn = false
	#Poison ivy damage?
	#Default: 0.5
	#Range: 0.0 ~ 1000.0
	poisonIvyDamage = 0.5
	#Poison ivy hurts on walk?
	#Default: true
	poisonIvyHurts = true
	#Flower drop chance
	#Default: 2
	#Range: 0 ~ 1000
	flowerDropChance = 2

	[block.ore]
		#Ruby ore harvest level
		#Default: 4
		#Range: 0 ~ 100
		rubyOreHarvestLevel = 4
		#Copper ore harvest level
		#Default: 1
		#Range: 0 ~ 100
		copperOreHarvestLevel = 1
		#Sapphire ore harvest level
		#Default: 3
		#Range: 0 ~ 100
		sapphireOreHarvestLevel = 3
		#Tin ore harvest level
		#Default: 1
		#Range: 0 ~ 100
		tinOreHarvestLevel = 1
		#Amber ore harvest level
		#Default: 3
		#Range: 0 ~ 100
		amberOreHarvestLevel = 3
		#Amethyst ore harvest level
		#Default: 2
		#Range: 0 ~ 100
		amethystOreHarvestLevel = 2
		#Malachite ore harvest level
		#Default: 3
		#Range: 0 ~ 100
		malachiteOreHarvestLevel = 3
		#Silver ore harvest level
		#Default: 3
		#Range: 0 ~ 100
		silverOreHarvestLevel = 3

